# Generated by Django 3.0.4 on 2020-06-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Categorie'),
        ),
        migrations.AddField(
            model_name='recette',
            name='commentaire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Commentaire'),
        ),
    ]
