# Generated by Django 3.0.4 on 2020-06-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0002_auto_20200625_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='commentaire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Commentaire'),
        ),
    ]
