# Generated by Django 3.0.4 on 2020-06-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0003_auto_20200625_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='etapes',
            field=models.TextField(default='Value', max_length=1000),
        ),
    ]
