# Generated by Django 3.0.4 on 2020-06-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0004_auto_20200626_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='commentaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Commentaire'),
        ),
    ]
