# Generated by Django 3.0.4 on 2020-06-26 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0005_auto_20200626_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='recette',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Recette'),
        ),
    ]
