# Generated by Django 3.0.4 on 2020-06-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0007_auto_20200626_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
