# Generated by Django 3.0.4 on 2020-06-27 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0008_commentaire_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
