# Generated by Django 3.0.4 on 2020-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0009_auto_20200627_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(default=None),
        ),
    ]
