# Generated by Django 3.0.4 on 2020-06-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0010_auto_20200627_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='totalVote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
