# Generated by Django 3.0.4 on 2020-06-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0011_auto_20200628_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='totalVote',
        ),
    ]
