# Generated by Django 3.0.7 on 2020-07-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BennaFood', '0012_remove_recette_totalvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BennaFood.Categorie'),
        ),
    ]
